name: efood_kitchen
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.0+0

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: any
  shared_preferences: ^2.0.15
  connectivity_plus: ^6.1.1
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.2
  country_code_picker: ^3.2.0
  vibration: ^3.1.3
  shimmer: ^2.0.0-nullsafety.0
  flutter_custom_clippers: ^2.0.0
  flutter_spinkit: ^5.1.0
  audioplayers: ^5.2.1
  http: ^1.2.1
  firebase_crashlytics: ^5.0.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.1.11
  flutter_foreground_task: ^8.13.0
  disable_battery_optimization:
    git:
      url: https://github.com/pvsvamsi/Disable-Battery-Optimizations
      ref: f34acdb


  collection: any
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900